DELETE http://localhost:3001/api/persons/1
###
GET http://localhost:3001/api/persons
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Manuel Perez",
    "number": "3465-521266"
}
